version: '2'
networks:
  world:
    external:
      name: www

services:

  nginx:
    image: nginx
    container_name: nginx
    environment:
      DEFAULT_HOST: core.muid.sh
    volumes:
      - /srv/etc/conf.d:/etc/nginx/conf.d
      - /srv/etc/vhost.d:/etc/nginx/vhost.d
      - /srv/share/html:/usr/share/nginx/html
      - /srv/certs:/etc/nginx/certs:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - world

  dockergen:
    image: jwilder/docker-gen
    container_name: dockergen
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/tmpl/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
    volumes_from:
      - nginx
    volumes:
      - /srv/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  simple-site:
    image: nginx
    container_name: default-site
    environment:
      - VIRTUAL_HOST=core.muid.sh
      - LETSENCRYPT_HOST=core.muid.sh
      - LETSENCRYPT_EMAIL=ewald@muthesius.de
      - VIRTUAL_NETWORK=www
      # - VIRTUAL_PORT=80
    networks:
      - world
