version: '2'
networks:
  www:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    volumes:
      - /srv/share/html:/usr/share/nginx/html
      - /srv/etc/conf.d:/etc/nginx/conf.d
      - /srv/etc/vhost.d:/etc/nginx/vhost.d
      - /srv/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - www
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - /srv/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
